### ISSUE TITLE
[Bug] Create Macro Stores the Wrong Camera Data the Falemos Cameras

### ISSUE THREAD

**Issue by Dick-K** [jvir/foundry-falemos#24]
1) I set up a 4 camera display, each player having a different frame image. I created a macro and stored it in the quickbar. 

2) I disabled _Falemos_.

3) I clicked on the macro and Falemos activated but 2 cameras were wrongly placed without their image frames and the GM camera was placed in the position of a player's camera with that player's frame.

**Comment by jvir** [comment]
Can you provide me with the macro? I suspect it is a bug in the Vaccinator integration.

**Comment by Dick-K** [comment]
Thanks jvir, your rapid response is very much appreciated:
I'm testing all this in a test copy of my main world.

Here is an export of a macro that was created by the/a previous version of Falemos (I had to tag .txt onto it so I could upload it).
[fvtt-Macro-Falemos_WorksOK.json.txt](https://github.com/jvir/foundry-falemos/files/6526597/fvtt-Macro-Falemos_WorksOK.json.txt)

This is what that looks like when I execute the macro, the correct view:
![image](https://user-images.githubusercontent.com/73724728/119230954-6dc16e80-bb16-11eb-92e5-c5ee851aec80.png)

I then created a macro in the new version of Falemos from that scene layout:

[fvtt-Macro-Falemos_Debug.json.txt](https://github.com/jvir/foundry-falemos/files/6526614/fvtt-Macro-Falemos_Debug.json.txt)

This is the result of executing that macro. As you can see, the Gamemaster camera frame has disappeared, one player is left as it was and the GM's camera view has replaced a player's camera while expanding the size of that player's frame:
![image](https://user-images.githubusercontent.com/73724728/119230590-d4458d00-bb14-11eb-9158-652ff055e82f.png)

Hope this helps, this is a great module!

**Comment by lozalojo** [comment]
Yup, looks like a problem with Vaccinator, because I've noticed from my tests the same issue, the problem is that at some point it gets confused by users and create new dummy camera setups at scene.db. In your case, there are 6 configurations when there are only 4 users, in fact configurations 1 and 3 seems dummy configurations, with no frame added.

When it tries to load the configuration again it does in order, so it loads those two dummy configurations, producing strange results.

Did you created the layout using Vaccinator macro o manually? Seems something related with the use of an internal function by Vaccinator.

**Comment by Dick-K** [comment]
Hi Jose, I originally created the layout manually in the Falemos scene configuration, and created a macro for it in an older version of Falemos.

The sequence of events was:
1) Experiment with Vaccinator
2) Use old macro created with older version of Falemos to recreate scene configuration, it worked fine
3) Change % camera width
4) Create new macro with latest version of Falemos
5) Use new macro, notice problem

Hope that all makes sense.

PS: regarding the number of configurations, I have several test users, 2 of which own multiple actors.

**Comment by jvir** [comment]
Hello, the problem is mine. The two functions that export and import scenes should be better sanitized, because right now the export does not export only the player configuration, but any other key that exists (and should not exist). On the other hand, the import function allows to create more keys than players, which should not be allowed either.

In short, although Vaccinator has an influence on this, the only responsibility is mine. I will soon release a version that I hope will fix it.

**Comment by Dick-K** [comment]
Thanks guys, it's not urgent, but your attention to detail is much appreciated.

**Comment by Dick-K** [comment]
I can confirm that macro creation is working correctly in Falemos v0.8.0. Nice job!
