### ISSUE TITLE
Usability Improvements

### ISSUE THREAD

**Issue by Dick-K** [jvir/foundry-falemos#5]
This is a great idea and works really well. Please accept the following as suggestions and not criticisms.

**Configuration Dialogue**
At the moment all configuration is awkwardly placed as part of the scene configuration, with a separate panel for each player.
_Suggestion_: A separate, single configuration panel, invoked from _Manage Modules_ that allows the GM to select the scene and player from drop-down lists.

**Global Configuration**
If there are 5 players (inc. GM) and 20 scenes, a fairly common game size, then there are potentially 100 separate panels, about 1600 data items, to specify.
_Suggestion_: Provide a means of specifying a global camera configuration or permit a Scene/Player configuration to be inherited from another Scene/Player configuration or perhaps a template.

**Sizing and Positioning**
The size and position of camera windows is numerically specified.
_Suggestion_: Permit persistent size and position to be specified using the mouse-drag in addition to the numerical apecification. Allow the _Name_ Y position to be specified as Left, Centre, Right, in addition to the numerical specification. Provide a permission setting that permits the player to do this.

Thanks for the great work and for reading this.

**Comment by jvir** [comment]
Hi, I love the suggestions! All are welcome.

I will give my opinion on them (my opinion is not immutable and may vary according to my knowledge and experience).

1.- Configuration Dialogue: Personally I like that being a module based on scenes this configuration is done from the scene configuration, the data is also saved in the scene itself which in my opinion makes everything more compact.

2.- Global Configuration: I agree that currently the configuration is heavy and long. It is planned for the future to make it simpler but I had to make a decision to release the module as soon as possible and I had to decide between simplicity and customization possibilities and I took the latter first (for the Alpha versions). In the future it is planned to offer macros with presets and copying settings between scenes.

3.- Sizing and Positioning: I like the possibility of using the mouse and it will be studied for future versions (without indicating times since I have enough functionalities thought and they will have priority). About the positioning of the name, it can be a good idea, but I have doubts if it will mess up even more the configuration, I will study it. Finally, regarding the user permissions, my idea is that the users don't have permissions to modify anything but the visibility of controls through the keyboard shortcut and something else that I have planned (the scene setting). The goal right now is to change from pixel sizes to relative sizes so that all players see exactly the same scene.

I confess that I should probably create a roadmap so that you can see what is planned so that I can also get feedback on that roadmap. I will create it in the next few days.

I welcome suggestions and feedback and this issue will remain open until suggestions are either completed or dismissed in a reasoned manner.

**Comment by Dick-K** [comment]
Thanks for giving this your consideration, I look forward to future developments.

**Comment by jvir** [comment]
In version 0.5.0 a button has been added to export the configuration to a macro for later reuse.

With this option you can:

- Create own scene presets.
- Apply presets another scenes.

I think this covers most of the issue, in the absence of a better experience for setting up a scene.

**Comment by Dick-K** [comment]
> In version 0.5.0 a button has been added to export the configuration to a macro for later reuse.
> 
> With this option you can:
> 
> * Create own scene presets.
> * Apply presets another scenes.
> 
> I think this covers most of the issue, in the absence of a better experience for setting up a scene.

That's great news, thanks so much for your hard work!
ETA: and the macro feature works really well...good work!

**Comment by jvir** [comment]
Hello Dick.
I am going to close this issue because I believe that most of it is complete. Feel free to open another one if you think something is not correct or should be improved.

**Comment by Dick-K** [comment]
Excellent work and support of your module. Thanks for being so understanding of the suggestions. I look forward to any future developments.
